### ISSUE TITLE
Timestamp changes after timezone change + remounting

### ISSUE THREAD

**Issue by wzyboy** [relan/exfat#70]
Hi,

I recently moved from a city in Asia/Shanhai (+0800) timezone to a city in America/New_York (-0400) timezone. During my regular photo backup (with rsync), I noticed all my old files are getting touched: their timestamps have been modified. I reproduced this:

![exfat-fuse-timezone-mount-bug](https://user-images.githubusercontent.com/459384/27981708-7a5cd080-635e-11e7-8f06-1a7e4caf5663.png)

As you can see: `/dev/mmcblk0p1` is an exFAT partition of my camera's SDXC. The first photo of my camera was taken at `2017-05-23 14:38+0800`. When I set timezone to Asia/Shanhai, the mtime of the photo file is correct.

As I set the system's timezone to America/New_York (-0400), I can see the mtime of the photo is still correct: `2017-05-23 14:38+0800` == `2017-05-23 02:38-0400`.

However, after I remount (umount + mount) the exFAT partition after the system timezone change, the mtime of the photo is incorrect: it reads `2017-05-23 14:38-0400` now. This is why all my old photos are getting touched by my rsync script after I moved from Asia to North America.

A quick Google search brought me to https://github.com/relan/exfat/issues/38 . As @relan [mentioned](https://github.com/relan/exfat/issues/38#issuecomment-228602922): exFAT prior to Windows 7 supports only timestamps in local time. I wonder if this is a lack of feature in filesystem itself or the filesystem driver? i.e. Is the problem I encountered caused by my camera (e.g. using an outdated exFAT version since the card is formatted by my camera) or by exfat-fuse driver?

**Comment by relan** [comment]
> exFAT prior to Windows 7 supports only timestamps in local time. I wonder if this is a lack of feature in filesystem itself or the filesystem driver?

This is fuse-exfat's fault that it does not support timezones for files timestamps. #38 is not related to this.

**Comment by wzyboy** [comment]
I see. I used to think that filesystem stores timestamps in a timezone-independant way, like Unix epoch time, and it is filesystem driver's job to calculate the local time according to system timezone settings. But after [reading](http://ntfs.com/exfat-time-stamp.htm) a bit, I can see that exFAT stores timestamp in local time and has a seperate field for timezone info.

May I ask if the support of timezone field is on the roadmap of fuse-exfat? Are there any workarounds (like extra mouting options) that deals situations similar to my case?

**Comment by relan** [comment]
There's no roadmap. :) And no workarounds, as far as I can see.

I'll have a look at this issue later.

**Comment by nhunsperger** [comment]
Lack of support for timezones recently caused me a lot of grief.  It especially didn't help that OS X was writing exFAT timestamps in UTC+7 instead of my local timezone of UTC-7.  So, this feature made my roadmap. :-)

**Comment by eharris** [comment]
This is causing me a lot of grief even though in my circumstances it's not the timezone that changes, but rather the time offset due to DST time starting/stopping.

I'm trying to do incremental backups of a very large directory tree to an exfat filesystem on a USB external drive using rsync.  I'm using exfat on the backup drive because I want the incremental backups to be readable on Windows systems natively without needing any specialized software.

But whenever the DST time changes (twice a year), rsync sees all the modification times of all the files have changed (by an hour) and copies the entire very large tree causing the backup to take forever, waste a lot of unnecessary space, and also eventually fail because it causes the destination to run out of space.

The workaround to this (and it's a pretty unacceptable workaround) is to force rsync to compare the contents of all the files rather than using the mtime, but that causes the backups to *always* take forever, and puts a lot of unnecessary disk load on the system which impacts the users of the system for long periods whenever backups are being run.  And I don't like being forced to run backups less often just because they are so expensive in terms of system resources and user impact.

**Comment by relan** [comment]
Timezone offsets should work properly after 75f28b558a1a86b45308a3e7d0af222624bc2c61.

**Comment by eharris** [comment]
Doesn't look like there's a release yet that includes that.  When might a new release be created that incorporates that fix?

**Comment by relan** [comment]
I plan to make a release before the end of the year. Need to incorporate a couple of fixes.

**Comment by wzyboy** [comment]
Thank you @relan for adding support for timezone in exfat-fuse! Maybe it is time to make a new release?

Off-topic but fun: today I tried the native (non-fuse) exFAT support that came with Linux 5.4 (I am using Linux 5.6). I found that the native exFAT driver could handle the timezone offset properly, but the *date* is off by one month. The first photo of my camera was taken on 2017-05-23 but with native exFAT driver the mtime shows 2017-06-23...

**Comment by AlexxIT** [comment]
@wzyboy I have this problem too

**Comment by SpiritsUnite** [comment]
Are there any plans for a new release? This seems to be affecting people on Chrome OS too.

**Comment by hoexter** [comment]
Hi, since Debian users seem to be around here as well: I've taken a discussion on debian-user regarding this issue as a motivation to upload a snapshot of what is in the exfat git repo to experimental.

**Comment by wzyboy** [comment]
I also made an AUR package that integrates the patch from #119 into the tagged release of 1.3.0. If you are an Arch Linux user and read this, you could try: https://aur.archlinux.org/packages/exfat-utils-timezone/

**Comment by biokomiker** [comment]
> The plain vanilla kernel 5.14.7 has similar problems with timestamps. I have disabled kernel exfat module loading (blacklisted) and added a symbolic link mount.exfat -> mount.exfat-fuse under /sbin in order to get mounting per mouse-click under Xfce.
> 

This works nicely here (Ubuntu 22.04). Blacklisting can be done easily via GRUB commandline, just add: modprobe.blacklist=exfat

**Comment by relan** [comment]
Fixed in v1.4.0.
