### ISSUE TITLE
FreeBSD fstab

### ISSUE THREAD

**Issue by pestalent1** [relan/exfat#94]
what is the proper entry to auto mount in fstab on FreeBSD?

**Comment by relan** [comment]
Unfortunately I've no idea how automounting works in FreeBSD.

**Comment by fhajji** [comment]
Do you mean automount(8) and autofs(5)?

Section "Automating Mounts with autofs(5)" of the Handbook may be what you're looking for:

https://www.freebsd.org/doc/handbook/network-nfs.html

**Comment by jbeich** [comment]
FreeBSD 11.1+ [should support](https://github.com/freebsd/freebsd/commit/3454d78e66e168df11f1b0b952f6a48e08a79e5f) exfat via autofs e.g.,
1. Install `sysutils/fusefs-exfat` (no prebuilt package due to patents)
2. Uncomment `/media -media ...` line in `/etc/auto_master`
3. Apply config changes via `service automount restart`
4. Browse `/media` after plugging the device using exfat

**Comment by relan** [comment]
The question was answered.
